format_version: 10
pipelines:
  CFS-COPT-live:
    group: v2_live_git
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    materials:
      git-3e52ebb:
        git: https://github.com/vijayk2018/gocd_vi_live
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Cprofile:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Cprofile:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:flat:cprofile
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:cfs:export-inr
                - /var/www/files/v2-laravel/artisan
                - refresh:cfs:export-usd
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:cprofile:logo
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:tscreate:cfscompanies
                command: php
                run_if: passed
          Plstandard:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:flat:cprofile
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:cfs:export-inr
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:cfs:export-usd
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:flat:cfs_ratio
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - alert:notifications
                command: php
                run_if: passed
          Balancesheet:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:cfs:export-inr
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:cfs:export-usd
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:flat:cfs_ratio
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - alert:notifications
                command: php
                run_if: passed
