format_version: 10
pipelines:
  CRM-v2:
    group: v2_live
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    timer:
      spec: 0 * * ? * *
      only_on_changes: false
    materials:
      git-a1a512d:
        git: https://github.com/vijayk2018/gocd_vi_live
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - CRM:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          CRM:
            timeout: 0
            resources:
            - agent-2
            tasks:
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - crmReply:refresh
                command: php
                run_if: passed
