format_version: 10
pipelines:
  Funds-v2:
    group: v2_live_git
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git-e61a711:
        git: https://github.com/vijayk2018/gocd_vi_live
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - FundNames:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Fund_Names:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:flat:funds
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:tscreate:funds
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:flat:refunds
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:tscreate:re_funds
                command: php
                run_if: passed
          Fund_Raising_Details:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:flat:funds
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:tscreate:funds
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:flat:refunds
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:tscreate:re_funds
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - alert:notifications
                command: php
                run_if: passed
