format_version: 10
pipelines:
  LimitedPartners-v2:
    group: v2_live
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git-2bae35b:
        git: https://github.com/vijayk2018/gocd_vi_live
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - LimitedPartners:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Limited_Partners:
            timeout: 0
            resources:
            - agent-2
            tasks:
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:tscreate:LP
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:lp:logo
                command: php
                run_if: passed
