format_version: 10
pipelines:
  REAdvisors-v2-live:
    group: v2_live_git
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    timer:
      spec: 0 */30 * ? * *
      only_on_changes: false
    materials:
      git-f8ebf0e:
        git: https://github.com/vijayk2018/gocd_vi_live
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - REAdvisors:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          RE_Advisors:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:tscreate:re_ladvisors
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:tscreate:re_tadvisors
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:readvisor:logo
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:create:re_adv_to_acquirers_filter_flat
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:create:re_adv_to_companies_filter_flat
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:create:re_adv_to_exits_filter_flat
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:create:re_adv_to_investors_filter_flat
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:create:re_adv_to_other_ma_acquirer_filter_flat
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:create:re_adv_to_other_ma_companies_filter_flat
                command: php
                run_if: passed
