format_version: 10
pipelines:
  REmanda-v2:
    group: v2_live_git
    label_template: ${COUNT}
    lock_behavior: lockOnFailure
    display_order: -1
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    materials:
      git-2771c1a:
        git: https://github.com/vijayk2018/gocd_vi_live
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - REmanda:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          REmanda:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:flat:re-exits
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:flat:re-profile
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:create:re_adv_to_acquirers_filter_flat
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:create:re_adv_to_exits_filter_flat
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:create:re_inv_exit_filter
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:tscreate:recompanies
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - redis:expire:pecompanies
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - alert:notifications
                command: php
                run_if: passed
          RE_manda_Investors:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:flat:re-exits
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:create:re_adv_to_acquirers_filter_flat
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:create:re_adv_to_exits_filter_flat
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:create:re_inv_exit_filter
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:tscreate:reinvestors
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:flat:re-investor-profile
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - refresh:tscreate:recompanies
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - redis:expire:investors
                command: php
                run_if: passed
            - exec:
                arguments:
                - /var/www/files/v2-laravel/artisan
                - alert:notifications
                command: php
                run_if: passed
